name: JRuby CI

on: [push, pull_request]

permissions:
  contents: read

jobs:

  rake-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ['test:jruby:int', 'spec:ruby:fast', 'spec:ji', 'spec:ffi', 'test:mri:core:jit', 'test:mri:extra', 'spec:ruby:fast:jit', 'test:mri:stdlib', 'spec:ruby:slow', 'spec:ruby:debug', 'test:jruby:aot', 'test:slow_suites', 'spec:compiler', 'spec:regression', 'spec:jruby', 'spec:jrubyc', 'spec:profiler']
        java-version: ['21', '23']
      fail-fast: false

    name: rake ${{ matrix.target }} (Java ${{ matrix.java-version }})

    steps:
      - name: checkout
        run: echo "hi"

  jruby-tests-dev:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      JRUBY_OPTS: '--dev'

    steps:
      - name: checkout
        run: echo "hi"

  rake-test-indy-off:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ['test:mri:core:jit', 'test:jruby:jit', 'spec:compiler', 'spec:ruby:fast:jit', 'spec:ji']
        java-version: ['21', '23']
      fail-fast: false

    name: rake ${{ matrix.target }} (Java ${{ matrix.java-version }} -indy)

    steps:
      - name: checkout
        run: echo "hi"

  mvn-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: mvn 

    steps:
      - name: checkout
        run: echo "hi"

  mvn-test-extended:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false


    name: mvn 

    steps:
      - name: checkout
        run: echo "hi"

  regression-specs-jit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      JRUBY_OPTS: '-Xjit.threshold=0'

    steps:
      - name: checkout
        run: echo "hi"

  mvn-test-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false


    steps:
      - name: checkout
        run: echo "hi"

  dependency-check:
    runs-on: ubuntu-latest

    name: Dependency check

    steps:
      - name: checkout
        run: echo "hi"

  test-versions:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: Verify build artifacts
    steps:
      - name: checkout
        run: echo "hi"

  sequel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: checkout
        run: echo "hi"

  concurrent-ruby:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: checkout
        run: echo "hi"

#  mvn-test-m1:
#    runs-on: [self-hosted, macos, aarch64]
#
#    strategy:
#      matrix:
#        package-flags: ['-Ptest']
#        # dist, complete, and osgi do not pass on 21 yet
#        java-version: ['11']
#      fail-fast: false
#
#    name: mvn ${{ matrix.package-flags }} (Java ${{ matrix.java-version }} Apple aarch64)
#
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - name: set up java ${{ matrix.java-version }}
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: ${{ matrix.java-version }}
#          architecture: arm
#      - name: bootstrap
#        run: ./mvnw -Pbootstrap clean package
#      - name: mvn package ${{ matrix.package-flags }}
#        run: tool/maven-ci-script.sh
#        env:
#          PHASE: 'package ${{ matrix.package-flags }}'
#
#  spec-m1:
#    runs-on: [self-hosted, macos, aarch64]
#
#    strategy:
#      matrix:
#        target: ['spec:ffi']
#        java-version: ['11']
#      fail-fast: false
#
#    name: rake ${{ matrix.target }} (Java ${{ matrix.java-version }} Apple aarch64)
#
#    steps:
#      - name: Bootstrap build
#        uses: jruby/jruby-ci-build@fbd2cf981aaff3eae190ac20086fa161be3d9060
#        with:
#          java-version: 21
#      - name: set up java ${{ matrix.java-version }}
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: ${{ matrix.java-version }}
#          architecture: arm
#          cache: 'maven'
#      - name: rake ${{ matrix.target }}
##        run: "bin/jruby -S rake ${{ matrix.target }}"
#        run: "true"

  maven-test-openj9-21:
    runs-on: ubuntu-latest

    name: mvn -Ptest (OpenJ9 Java 21)

    steps:
      - name: checkout
        run: echo "hi"

  jruby-shell-check:
    runs-on: ubuntu-latest

    name: shellcheck jruby.sh

    steps:
      - name: checkout
        run: echo "hi"

  publish-snapshot:
    permissions:
      contents: read
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/10-dev' }}
    needs: [mvn-test, mvn-test-extended, mvn-test-windows, dependency-check, rake-test, rake-test-indy-off, rake-test, test-versions, sequel, concurrent-ruby, jruby-tests-dev, regression-specs-jit]
    uses: jruby/jruby/.github/workflows/snapshot-publish.yml@d8369e218d4878b79d394a90483f109a2096a820
    with:
      javaLevel: 21
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
